import { describe, it, expect } from 'vitest';
import {
  foldSalesReturnsByReason, foldCreditNotesByReason, mergeReasonLines,
  type SalesReturnRaw, type CreditNoteRaw,
} from '@/lib/returns-analysis';

/**
 * Z3 — the credit note became the document, so Returns Analysis has to read
 * BOTH sources: sales returns raised before the switch, credit notes raised
 * after. A report that silently loses history on the day of a refactor is
 * worse than one that was never built.
 *
 * The two hazards are the fold (header figures counted once per document, not
 * once per line) and the overlap (a note generated BY a return must not be
 * counted on both sides).
 */

const ret = (over: Partial<SalesReturnRaw> = {}): SalesReturnRaw => ({
  reason: 'wrong_part',
  restocking_fee: 0,
  credit_notes: { total_amount: 100 },
  sales_return_items: [{ qty_returned: 2, condition: 'resellable', unit_cost: 10 }],
  ...over,
});

const note = (over: Partial<CreditNoteRaw> = {}): CreditNoteRaw => ({
  reason: 'return',
  restocking_fee: 0,
  total_amount: 100,
  credit_note_items: [{ quantity: 2, condition: 'resellable', cost_at_sale: 10 }],
  ...over,
});

describe('credit note fold', () => {
  it('counts the note total once, not once per line', () => {
    // The trap: adding a header figure inside the item loop multiplies it by
    // the line count, which looks plausible and is wrong.
    const out = foldCreditNotesByReason([note({
      total_amount: 300,
      restocking_fee: 15,
      credit_note_items: [
        { quantity: 1, condition: 'resellable', cost_at_sale: 10 },
        { quantity: 1, condition: 'resellable', cost_at_sale: 20 },
        { quantity: 1, condition: 'resellable', cost_at_sale: 30 },
      ],
    })]);
    expect(out[0]!.credit_value).toBe(300);   // not 900
    expect(out[0]!.fees).toBe(15);            // not 45
    expect(out[0]!.qty).toBe(3);              // per line, correctly
    expect(out[0]!.restocked_value).toBe(60);
  });

  it('splits damaged cost out the way phase89 posts it', () => {
    // Damaged cost is debited to 6700 Inventory Loss; the rest went back on
    // the shelf. The report has to show the same split the ledger does.
    const out = foldCreditNotesByReason([note({
      credit_note_items: [
        { quantity: 2, condition: 'damaged',    cost_at_sale: 10 },
        { quantity: 3, condition: 'resellable', cost_at_sale: 10 },
      ],
    })]);
    expect(out[0]!.written_off).toBe(20);
    expect(out[0]!.restocked_value).toBe(30);
  });

  it('treats a missing condition as resellable, like the column default', () => {
    const out = foldCreditNotesByReason([note({
      credit_note_items: [{ quantity: 1, condition: null, cost_at_sale: 40 }],
    })]);
    expect(out[0]!.restocked_value).toBe(40);
    expect(out[0]!.written_off).toBe(0);
  });

  it('survives a note with no lines at all', () => {
    const out = foldCreditNotesByReason([note({ credit_note_items: null })]);
    expect(out[0]!.returns).toBe(1);
    expect(out[0]!.qty).toBe(0);
  });
});

describe('merging the two sources', () => {
  it('adds a reason that exists on both sides rather than listing it twice', () => {
    // This is what makes the report continuous across the switch: a company
    // that returned goods before AND after sees one row, not two.
    const out = mergeReasonLines(
      foldSalesReturnsByReason([ret({ reason: 'damaged' })]),
      foldCreditNotesByReason([note({ reason: 'damaged', total_amount: 50 })]),
    );
    expect(out).toHaveLength(1);
    expect(out[0]!.reason).toBe('damaged');
    expect(out[0]!.returns).toBe(2);
    expect(out[0]!.credit_value).toBe(150);
    expect(out[0]!.qty).toBe(4);
  });

  it('keeps distinct reasons apart and sorts by value', () => {
    const out = mergeReasonLines(
      foldSalesReturnsByReason([ret({ reason: 'wrong_part' })]),
      foldCreditNotesByReason([note({ reason: 'rebate', total_amount: 500 })]),
    );
    expect(out.map(r => r.reason)).toEqual(['rebate', 'wrong_part']);
  });

  it('is a no-op on empty sets', () => {
    expect(mergeReasonLines([], [])).toEqual([]);
  });

  it('never double-counts a note that came from a return', () => {
    // The adapter excludes return-generated notes before folding. If that
    // filter were dropped, this is the shape of the damage: one physical
    // return reported as two, at twice the value.
    const both = mergeReasonLines(
      foldSalesReturnsByReason([ret({ reason: 'return' })]),
      foldCreditNotesByReason([note({ reason: 'return' })]),   // the SAME event
    );
    expect(both[0]!.returns).toBe(2);
    expect(both[0]!.credit_value).toBe(200);
    // Filtered, as the adapter does it: one event, counted once.
    const filtered = mergeReasonLines(
      foldSalesReturnsByReason([ret({ reason: 'return' })]),
      foldCreditNotesByReason([]),
    );
    expect(filtered[0]!.returns).toBe(1);
    expect(filtered[0]!.credit_value).toBe(100);
  });
});

/**
 * Z6 — the purchase-side mirror. Same two hazards, same answers.
 */
describe('debit note fold', () => {
  const dn = (over: Partial<import('@/lib/returns-analysis').DebitNoteRaw> = {}) => ({
    reason: 'return',
    total_amount: 100,
    debit_note_items: [{ quantity: 2, unit_cost: 10 }],
    ...over,
  });

  it('counts the note total once, not once per line', async () => {
    const { foldDebitNotesByReason } = await import('@/lib/returns-analysis');
    const out = foldDebitNotesByReason([dn({
      total_amount: 300,
      debit_note_items: [
        { quantity: 1, unit_cost: 10 },
        { quantity: 1, unit_cost: 20 },
        { quantity: 1, unit_cost: 30 },
      ],
    })]);
    expect(out[0]!.debit_value).toBe(300);   // not 900
    expect(out[0]!.qty).toBe(3);
    expect(out[0]!.cost).toBe(60);
  });

  it('merges with the legacy purchase-return side instead of listing twice', async () => {
    const { foldPurchaseReturnsByReason, foldDebitNotesByReason, mergePurchaseReasonLines } =
      await import('@/lib/returns-analysis');
    const out = mergePurchaseReasonLines(
      foldPurchaseReturnsByReason([{
        reason: 'damaged',
        debit_notes: { total_amount: 100 },
        purchase_return_items: [{ qty_returned: 2, unit_cost: 10 }],
      }]),
      foldDebitNotesByReason([dn({ reason: 'damaged', total_amount: 50 })]),
    );
    expect(out).toHaveLength(1);
    expect(out[0]!.returns).toBe(2);
    expect(out[0]!.debit_value).toBe(150);
    expect(out[0]!.qty).toBe(4);
  });
});
